server:
  port: 9006
spring:
  application:
    name: leadnews-comment

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.133:8848

  data:
    mongodb:
      host: 192.168.66.133
      port: 27017
      database: leadnews-comment