server:
  port: 9004
spring:
  application:
    name: leadnews-article
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.133:3306/leadnews_article?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.133:8848

    alibaba:
      seata:
        tx-service-group: ${spring.application.name}_tx_group  # 定义seata注册时的组名

  kafka:
    bootstrap-servers: 192.168.66.133:9092
    consumer:
      group-id: ${spring.appication.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.article.pojos
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名法
  global-config:
    datacenter-id: 1
    worker-id: 1

logging:
  level:
    com.heima.article: debug