server:
  port: 9007
spring:
  application:
    name: leadnews-search
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.66.133:3306/leadnews_search?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.133:8848

  elasticsearch:
    rest:
      uris:
        - http://192.168.66.133:9200

  kafka:
    bootstrap-servers: 192.168.66.133:9092
    consumer:
      group-id: ${spring.appication.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.search.pojos
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名法

logging:
  level:
    com.heima.search: debug
